package protocol

import (
	"bufio"
	"encoding/binary"
	"fmt"
	"io"
)

// Request decoding is intentionally streaming. bufio.Reader lets a caller
// process half-packets and coalesced packets without making assumptions about
// TCP segmentation. Length checks happen before allocation and are shared by
// the client and server paths. The command byte is kept opaque until dispatch,
// allowing the protocol package to remain independent from storage, routing,
// and metrics. Extra is interpreted by individual commands: SET and EXPIRE
// treat it as seconds, TTL ignores it, and administrative commands reserve it
// for counters. Sequence numbers are caller-owned and are never generated by
// the codec. This separation makes request values easy to fuzz and serialize
// in unit tests while preserving a small, dependency-free wire implementation.

const Magic byte = 0xDC

type Request struct {
	Seq        uint32
	Cmd        Command
	Key, Value []byte
	Extra      uint64
}

func NewRequest(cmd Command, key string, value []byte, extra uint64) Request {
	return Request{Cmd: cmd, Key: []byte(key), Value: append([]byte(nil), value...), Extra: extra}
}
func (r Request) KeyString() string       { return string(r.Key) }
func (r Request) ValueString() string     { return string(r.Value) }
func (r Request) Valid() error            { return Validate(r.Cmd, r.Key, r.Value, r.Extra) }
func (r *Request) SetSequence(seq uint32) { r.Seq = seq }
func (r *Request) SetTTL(seconds uint64)  { r.Extra = seconds }
func (r Request) PayloadSize() int        { return len(r.Key) + len(r.Value) }
func (r Request) Clone() Request {
	return Request{Seq: r.Seq, Cmd: r.Cmd, Key: append([]byte(nil), r.Key...), Value: append([]byte(nil), r.Value...), Extra: r.Extra}
}
func (r Request) IsMutation() bool       { return !r.Cmd.ReadOnly() }
func (r Request) IsEmpty() bool          { return len(r.Key) == 0 && len(r.Value) == 0 && r.Extra == 0 }
func (r Request) Summary() string        { return r.Cmd.String() + " " + r.KeyString() }
func (r Request) IsSet() bool            { return r.Cmd == CmdSet }
func (r Request) IsGet() bool            { return r.Cmd == CmdGet }
func (r Request) IsDelete() bool         { return r.Cmd == CmdDel }
func (r Request) IsKeyQuery() bool       { return r.Cmd == CmdKeys }
func (r Request) IsPing() bool           { return r.Cmd == CmdPing }
func (r Request) HasKey() bool           { return len(r.Key) > 0 }
func (r Request) HasValue() bool         { return len(r.Value) > 0 }
func (r Request) TTLSeconds() uint64     { return r.Extra }
func (r Request) CommandName() string    { return r.Cmd.String() }
func (r Request) KeyLength() int         { return len(r.Key) }
func (r Request) ValueLength() int       { return len(r.Value) }
func (r Request) SequenceNumber() uint32 { return r.Seq }
func (r *Request) Clear()                { r.Key = nil; r.Value = nil; r.Extra = 0 }
func (r *Request) SetKey(key string)     { r.Key = []byte(key) }
func (r *Request) SetValue(value string) { r.Value = []byte(value) }
func (r Request) IsValid() bool          { return r.Valid() == nil }

func (r *Request) Encode(w io.Writer) error {
	if len(r.Key) > 1<<20 || len(r.Value) > 1<<24 {
		return fmt.Errorf("payload too large")
	}
	h := make([]byte, 28)
	h[0] = Magic
	h[1] = 1
	h[2] = byte(r.Cmd)
	binary.BigEndian.PutUint32(h[4:8], r.Seq)
	binary.BigEndian.PutUint32(h[8:12], uint32(len(r.Key)))
	binary.BigEndian.PutUint32(h[12:16], uint32(len(r.Value)))
	binary.BigEndian.PutUint64(h[16:24], r.Extra)
	if _, e := w.Write(h); e != nil {
		return e
	}
	if _, e := w.Write(r.Key); e != nil {
		return e
	}
	_, e := w.Write(r.Value)
	return e
}
func DecodeRequest(rd *bufio.Reader) (Request, error) {
	var h [28]byte
	if _, e := io.ReadFull(rd, h[:]); e != nil {
		return Request{}, e
	}
	if h[0] != Magic {
		return Request{}, fmt.Errorf("bad magic")
	}
	k, v := binary.BigEndian.Uint32(h[8:12]), binary.BigEndian.Uint32(h[12:16])
	if k > 1<<20 || v > 1<<24 {
		return Request{}, fmt.Errorf("payload too large")
	}
	r := Request{Seq: binary.BigEndian.Uint32(h[4:8]), Cmd: Command(h[2]), Extra: binary.BigEndian.Uint64(h[16:24]), Key: make([]byte, k), Value: make([]byte, v)}
	_, e := io.ReadFull(rd, r.Key)
	if e != nil {
		return r, e
	}
	_, e = io.ReadFull(rd, r.Value)
	return r, e
}
